### ISSUE TITLE
Un remboursement échoué passe en statut remboursé à tort

### ISSUE THREAD

**Issue by lamiaammiali** [OystParis/oyst-prestashop#10]
@lamiaammiali commented on [Mon Mar 20 2017](https://github.com/OystParis/prestashop-deployment/issues/1)

@lamiaammiali commented on [Mon Mar 20 2017](https://github.com/OystParis/catalog-api/issues/70)

description :

on effectue un remboursement dans prestashop, mais le remboursement de la transaction renvoi un faillure.

voir pj

Attendu: 
si le remboursement échoue, le statut de la transaction doit rester à paiement accépté.

Obtenu:

le statut de la transaction est passé à remboursé dans le bo prestashop.

![image](https://cloud.githubusercontent.com/assets/22000242/24112141/d7b44450-0d98-11e7-8401-2228b4d23230.png)

![image](https://cloud.githubusercontent.com/assets/22000242/24112181/01d89b64-0d99-11e7-9e7f-4853fad67630.png)

![image](https://cloud.githubusercontent.com/assets/22000242/24112250/3b3bf23e-0d99-11e7-8e7d-ffa7298a1e35.png)

**Comment by FabienSerny** [comment]
Je regarde ce qu'il en est

**Comment by FabienSerny** [comment]
Corrigé sur branche feat-freepay

**Comment by lamiaammiali** [comment]
correction ok
