### ISSUE TITLE
Statut de commande PS incohérent lors d'un remboursement partiel depuis BO FREEPAY

### ISSUE THREAD

**Issue by lamiaammiali** [OystParis/oyst-prestashop#110]
On effectue des remboursement partiel depuis le BO FREEPAY

On constate que les statuts de la commande remboursé partiellement est "Remboursé" au lieu de "remboursé partiellement"

![image](https://cloud.githubusercontent.com/assets/22000242/26316369/55d26c34-3f14-11e7-98f0-ba9df64a5793.png)

**Comment by quentinjunior** [comment]
Ok pour moi sur presta 1.6 en uploadant sur les deux versions 1.0.1 et 0.8.12
