### ISSUE TITLE
Wording en anglais sur remboursement partiel

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#111]
Le bouton remboursement partiel est en anglais et non en français

![image](https://cloud.githubusercontent.com/assets/27730079/26316591/09eb4830-3f15-11e7-9abd-18aef4d496ca.png)

**Comment by itkg-ndecraene** [comment]
NB : Tout ce qui concerne le plugin (+ le menu à gauche) est en français tout le reste est en anglais.

**Comment by quentinjunior** [comment]
Je close
