### ISSUE TITLE
ETQU, lorsque 1-click et FreePay sont activés, je ne peux pas utiliser FreePay

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#117]
## Détails:

En tant que marchand, lorsque 1-click et FreePay sont activés, je ne peux pas utiliser FreePay.

### Given:

* J'active FreePay
* J'active 1-click

![image](https://cloud.githubusercontent.com/assets/27730079/26551333/4e275850-4482-11e7-9394-9ba1999c1309.png)

### Then:

* Je passe une commande 1-click, cela fonctionne
* Je passe par Payer par carte bancaire, cela échoue

![image](https://cloud.githubusercontent.com/assets/27730079/26551380/887c9362-4482-11e7-8b2e-ca8e221e8f6e.png)

### Idée/piste:

Je pense que les deux branches n'ont pas été mergé et que c'est la cause de ce bug

**Comment by vschoener** [comment]
De ce que je sais, les deux méthodes ne sont pas liés. J

**Comment by itkg-ndecraene** [comment]
Ce n'est pas un bug, c'est juste qu'il y a eu des features sur la branche 1-click qui n'ont pas été appliqué au FreePay. Ça sera réglé au merge de FreePay et 1-click.
