### ISSUE TITLE
L'annulation coté bo n'est pas prise en compte dans prestashop

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#12]
Pour reproduire:
1. Passer une commande sur Prestashop 
2.  Annuler le paiement depuis le backoffice admin
3. La commande n'est pas annulée dans Prestashop

**Comment by FabienSerny** [comment]
@jonasmaumene Ce n'est actuellement pas possible en l'état actuel avec les webservices de Oyst. Il faut soit que vous prévoyez la possibilité d'appeler un webhook chez nous soit que nous ayons la possibilité d'interroger Oyst sur l'état d'une commande (la première solution étant la meilleure)

**Comment by itkg-ndecraene** [comment]
Il y a déjà un système de notification qui fonctionne.

Comme vu avec Jonas cela fonctionne. Il y a juste un petit problème de notifications => plusieurs notifications sont envoyés depuis le BO freepay pour l'AUTHORIZATION et CANCELLATION.

**Comment by FabienSerny** [comment]
Ah ok, je vais m'en occuper alors :)

**Comment by lamiaammiali** [comment]
ok corrigé
