### ISSUE TITLE
Le bouton remboursement standard reste actif à tort 

### ISSUE THREAD

**Issue by lamiaammiali** [OystParis/oyst-prestashop#13]
J’effectue un remboursement depuis la boutique Prestashop. 

Le remboursement est correctement effectué coté Oyst et coté prestashop

Attendu:

Le bouton remboursement standard ne doit plus être actif sur une transaction remboursée avec succès.

Obtenu:

Le bouton remboursement standard reste actif à tort 

![image](https://cloud.githubusercontent.com/assets/22000242/24156791/dbbae2f6-0e57-11e7-99ca-0500b98ee053.png)

![image](https://cloud.githubusercontent.com/assets/22000242/24156878/1d041a48-0e58-11e7-8f7c-d8d225140569.png)

**Comment by FabienSerny** [comment]
Corrigé sur la branche feat-freepay

**Comment by lamiaammiali** [comment]
correction ok
