### ISSUE TITLE
Redirection success/cancel/ error KO 

### ISSUE THREAD

**Issue by lamiaammiali** [OystParis/oyst-prestashop#14]
https://oystteam.atlassian.net/browse/PRES-14

Je configure une url custom sur le plugin de ma boutique Prestashop.
![image](https://cloud.githubusercontent.com/assets/22000242/24158289/24d3b77a-0e5c-11e7-8c88-c19d77c4523d.png)
![image](https://cloud.githubusercontent.com/assets/22000242/24158792/956dc858-0e5d-11e7-9f58-36764917d2e7.png)

![image](https://cloud.githubusercontent.com/assets/22000242/24158803/a06eb9b0-0e5d-11e7-8af6-145467cdcc09.png)

j'effectue un paiement en erreur (+ de 3 tentatives), 

Attendu:
Après l’échec de mon paiement je suis censé être redirigé sur l'url configuré

Obtenu:
Je suis redirigé sur la page 

NB: La redirection en cas de succès est  erronée aussi. car on est redirigé systématiquement sur la page, confirmation de commande et non sur l'historique de commande comme indiqué dans le plugin.

**Comment by itkg-ndecraene** [comment]
@lamiaammiali du coup, comme vu ensemble hier soir, il n'y a plus de bug?

**Comment by lamiaammiali** [comment]
ce n'est plus un bug oui
