### ISSUE TITLE
Bug script staging dans le module de production

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#141]
## Détails:

Un script appelle https://cdn.staging.oyst.eu alors que le module installé est un module de prod, et ou la clé API est aussi en prod

![pasted image at 2017_06_02 04_26 pm](https://cloud.githubusercontent.com/assets/27730079/26731424/5e25e9ee-47b4-11e7-8cc1-45172a419b7b.png)

### Corrections:

Mettre le bon script

**Comment by itkg-ndecraene** [comment]
Je suppose que l'URL doit varier suivant l'environnement (prod, preprod et custom)?
Si c'est le cas il faut prévoir un endroit où configurer l'URL du script JS.
