### ISSUE TITLE
Forcer le clean des caches lors de l'installation d'un module freepay ou 1-click

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#146]
## Détails:

En tant que marchand, lorsque j'installe un nouveau module j'ai des bugs comme par exemple le nom affichage du champ pour renseigner la clé API. Cela est dû aux caches qui ne sont pas cleaner.

Aujourd'hui on est obligé de notifier le marchand pour qu'il le fasse

## To Do:

Lors de l'installation du module, il faut forcer le clean des caches sur le BO du marchand

**Comment by Nightmare75** [comment]
> Je fini un test sur 1.6.
J'utilise la classe AddJS et AddCSS de PrestaShop afin que ça passe par les outils de base.
Avant, c'était directement inclus dans le fichier .tpl.
Quoi qu'il arrive, il faut que l'on ajoute dans la documentation technique qu'il est conseillé de vider le cache après la mise à jour du module.
