### ISSUE TITLE
affichage du bouton 1-click alors qu'il est désactivé depuis la config BO prestashop

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#148]
ETQM, une fois l'import catalogue fait, je désactive 1click depuis la config
Cependant le bouton est toujours sur mes fiches produits

**Comment by itkg-ndecraene** [comment]
Doublon de #93?

**Comment by quentinjunior** [comment]
Ok c'est une feature pas encore faite
