### ISSUE TITLE
Refonte du back office prestashop pour la configuration

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#168]
# Détail:

Aucun nouveau champ est nécessaire, c'est uniquement un changement assez profond des différents blocs. 
Des contraintes sont à ajouter sur le bouton "exporter mon catalogue" qui sera traité dans un autre ticket.
Un ticket sera aussi traité à part pour pouvoir choisir des environnements différents entre freepay et 1-click (ex: freepay en production et 1-click en staging)

## Etape 1:

Actuellement il y a le logo FreePay en haut de la configuration:

![image](https://user-images.githubusercontent.com/27730079/27131763-5f2c3d3c-510c-11e7-9752-9d5937153a4c.png)

 Il faut le remplacer par la photo ci dessous puisque le 1-click sera dans le module:

![logo-multi](https://user-images.githubusercontent.com/27730079/27131791-87da483c-510c-11e7-8a23-28ac87bbc916.png)

![image](https://user-images.githubusercontent.com/27730079/27131830-b4975aae-510c-11e7-930e-9af84424f906.png)

## Etape 2:

Créer deux onglets: FreePay et 1-Click ou iront les informations relatives à chaque module:

![image](https://user-images.githubusercontent.com/27730079/27132114-e00b79d0-510d-11e7-9770-9ec4828c10ed.png)

#### FreePay:

Changer le nom clé API production/pre-production/custom par clé API FreePay production/pre-production/custom

#### 1-Click:

Changer le nom clé API production/pre-production/custom par clé API 1-Click production/pre-production/custom

#### Agencement des champs dans la section FreePay:

Cf image ci dessous (pas de changement par rapport à la version actuelle)
![image](https://user-images.githubusercontent.com/27730079/27133466-718b8d06-5112-11e7-901a-20b7690d8dff.png)

#### Agencement des champs dans la section 1-Click:

Cf image ci dessous:

* changement du wording et de l'emplacement du bouton 'ajouter un mode de livraison situé en dessous et changement wording
* Le bouton synchronisation du catalogue apparait en dessous du bloc FreePay et 1-click

![image](https://user-images.githubusercontent.com/27730079/27133682-569c90ac-5113-11e7-9994-8104f084df89.png)

## Etape 5:

* Changement de position des champs du formulaire des modes de livraisons pour expoiter l'horizontalité de l'écran
* Enlever le champ : zone France-métropolitaine

![image](https://user-images.githubusercontent.com/27730079/27133584-ed4b5e62-5112-11e7-85d5-0ea7348f5160.png)

## Etape 6:

Le bouton exporter mon catalogue se situe en dessous du bouton sauvegarder. Il est non cliquable par défaut. Il peut être activé uniquement si un certains nombres de conditions sont remplies.

**Comment by vschoener** [comment]
A convertir en epique puis la découper proprement pour avoir des tâches distincts

**Comment by quentinjunior** [comment]
Retour QA:

## 1:
![image](https://user-images.githubusercontent.com/27730079/27394320-07713a7a-56ac-11e7-8be0-acb765766b54.png)

## 2:
![image](https://user-images.githubusercontent.com/27730079/27394322-0bb76eec-56ac-11e7-8942-ce31ac39f569.png)

## 3:
![image](https://user-images.githubusercontent.com/27730079/27394329-10f889a4-56ac-11e7-933a-3545d59379e6.png)

## 4:
![image](https://user-images.githubusercontent.com/27730079/27394334-1541d65a-56ac-11e7-840e-236066ee9529.png)

## 5:
![image](https://user-images.githubusercontent.com/27730079/27394338-1a131fc2-56ac-11e7-9f18-e38231e5d675.png)

**Comment by quentinjunior** [comment]
Ok pour moi
