### ISSUE TITLE
Supprimer error URL et Renommer cancel url en error URL

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#17]
@jonasmaumene commented on [Wed Mar 22 2017](https://github.com/OystParis/prestashop-deployment/issues/2)

![image](https://cloud.githubusercontent.com/assets/25003742/24192554/a248a77c-0eef-11e7-985f-5fb53f2eec7d.png)

**Comment by lamiaammiali** [comment]
validé
