### ISSUE TITLE
Statut échec de paiement sur les commandes 1-click V2 passées avec des frais de livraisons payants

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#176]
En tant que client je apsse une commande 1-click. Je choisis un mode de livraison payant. 

En tant que marchand, quand je regarde la commande en détail, j'observe dans l'historique le statut échec de paiement alors que la compta est bonne:
![image](https://user-images.githubusercontent.com/27730079/27180644-afaf8098-51d4-11e7-8438-f5a5f8c2b104.png)

Ce bug n'apparait pas lorsque les frais de livraison sont gratuits:
![image](https://user-images.githubusercontent.com/27730079/27180666-cbf96200-51d4-11e7-85aa-8deb0c1c89a3.png)

### Attendu:

trouver l'erreur et gérer les commandes avec les frais de livraison payants.

**Comment by vschoener** [comment]
Fixed during another work progress

**Comment by quentinjunior** [comment]
J'ai toujours le bug avec le dernier zip que tu m'as donné
![image](https://user-images.githubusercontent.com/27730079/27231082-ac19fe4e-52b1-11e7-9474-c31a209096f5.png)

**Comment by vschoener** [comment]
Can't reproduce

<img width="948" alt="screen shot 2017-06-19 at 10 44 59" src="https://user-images.githubusercontent.com/1213200/27277852-f211b100-54df-11e7-9f64-b46b54559146.png">
<img width="1878" alt="screen shot 2017-06-19 at 10 45 12" src="https://user-images.githubusercontent.com/1213200/27277853-f2189678-54df-11e7-97b1-2e41dbdf0f04.png">

**Comment by quentinjunior** [comment]
Je n'ai plus le statut échec de paiement, mais dans le récapitulatif de commande, j'ai encore une différence entre les paiements avec frais de port gratuits et avec frais de port payants

![image](https://user-images.githubusercontent.com/27730079/27319552-5c0ee426-5592-11e7-8a4b-29037632287d.png)

**Comment by quentinjunior** [comment]
J'ai de plus en tant que user un mail indiquant qu'une erreur de paiement est survenue

![image](https://user-images.githubusercontent.com/27730079/27341819-a3ee139c-55de-11e7-8adc-fe321666d44f.png)

![image](https://user-images.githubusercontent.com/27730079/27341835-b6417d90-55de-11e7-9232-10302e1c6e72.png)

**Comment by quentinjunior** [comment]
Comme je le pensais, sur pg admin les frais de ports sont nuls et non pas de 10 euros. D’où l’échec de paiement. Vincent as tu mis ce status par défaut pour empêcher de voir le bug ?
![image](https://user-images.githubusercontent.com/27730079/27342192-af4efd4a-55df-11e7-85db-ba57ba685685.png)
Sur freepay le prix indiqué comprend les frais de ports:
![image](https://user-images.githubusercontent.com/27730079/27342242-d92462e0-55df-11e7-8b02-286493d40cfe.png)

A voir d'ou vient le bug du coup
