### ISSUE TITLE
Importation du catalogue incomplète pour gros catalogue

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#179]
problème avec la gateway (error 502 et 504) ce produit pour des gros catalogues (enkr, legendicon)

La gateway renvoie une 502 ou une 504 pour l'import de catalogue trop grand. 
Il faut diminuer la taille du payload et regarder si le bug persiste.

To do : 

Changer la constante dans export product service

**Comment by Nightmare75** [comment]
"ça passe quand on le met à const EXPORT_REGULAR_NUMBER = 20;". à 100 ça ne fonctionne pas.
