### ISSUE TITLE
Envoyer les informations des déclinaisons au moment de l'export de catalog

### ISSUE THREAD

**Issue by Marcpepe** [oystparis/oyst-prestashop#185]
Il faut envoyer les informations des déclinaisons (sku) au moment de l'export de catalog. Le format doit être le suivant : 

![image](https://user-images.githubusercontent.com/4925054/27295739-3b4c02e2-551e-11e7-9efe-6f340c868485.png)

**Comment by vschoener** [comment]
@Marcpepe Tu aurais la doc contenant tous les champs possible à mettre ?
