### ISSUE TITLE
MAJ du nom des méthodes de livraisons

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#188]
## Détails:

En tant que marchand, quand je modifie le nom d'un transporteur, cela ce met bien à jour dans la configuration du 1-click.

![image](https://user-images.githubusercontent.com/27730079/27371340-ae3aa75c-5660-11e7-85a1-bb6370be3e71.png)
![image](https://user-images.githubusercontent.com/27730079/27371347-b1bdee2a-5660-11e7-8a09-a5dd00d435e6.png)
![image](https://user-images.githubusercontent.com/27730079/27371350-b518a452-5660-11e7-8c6f-cd5b6beffda2.png)

Cependant quand je sauvegarde la conf, je n'observe pas de changement sur la modale

![image](https://user-images.githubusercontent.com/27730079/27371367-caefeed4-5660-11e7-85c2-b87cdabaef82.png)

**Comment by vschoener** [comment]
Le comportement est 'normal', ça n'a pas été géré à ce niveau la, aucun hook n'a été mis en place pour répercuter les changements sur Oyst. Il faut resoumettre tout le formulaire

**Comment by quentinjunior** [comment]
Ok, qu'entends tu par resoumettre tout le formulaire?

**Comment by quentinjunior** [comment]
Car même après avoir supprimer le module 1-click V2 , puis j'ai réinstaller la V1.1 (freepay) puis en ré-installant le 1-click V2, j'observe toujours l'ancien nom sur la modale

**Comment by quentinjunior** [comment]
Ok je valide
