### ISSUE TITLE
Je suis systématiquement redirigé vers la page historique de commande Prestashop 1.5

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#20]
En tant qu'acheteur, je suis systématiquement redirigé vers la page d'historique de commande après avoir réussi un paiement.

**Comment by FabienSerny** [comment]
Je n'arrive pas à reproduire le bug pour le moment.
Je continue mes tests

**Comment by FabienSerny** [comment]
Es tu sûr d'avoir configuré l'option d'url de retours ?

<img width="702"  src="https://cloud.githubusercontent.com/assets/1514353/24745320/8a0e10e4-1ab5-11e7-8057-6c31d051f9da.png">

**Comment by jonasmaumene** [comment]
Oui je te confirme quelquesoit la valeur que je renseigne dans Success URL je tombe sur la page d'historique de commande

**Comment by FabienSerny** [comment]
J'ai trouvé l'origine du problème.
Sur PrestaShop 1.5, PrestaShop vérifie que le libellé de paiement correspond au nom du module
  if ($order->payment != $module->displayName)
                        Tools::redirect($redirectLink);

Dans le cas présent cela donne : 
CB != FreePay

Il redirige donc automatiquement vers la page d'historique de commande car il considère qu'il y a une erreur (ce qui n'est pas le cas, mais c'est ainsi que le controller Order-Confirmation fonctionne sur PS 1.5).

Le problème c'est qu'il a été demandé de préciser "CB" en temps que mode de paiement.
La solution la plus simple que j'ai trouvé c'est de remettre "FreePay" lors de la validation de commande (ce qui fait que la commande apparaîtra comme payé via "FreePay" au lieu de "CB" dans le BO). A terme, on pourra toujours créer notre propre page de confirmation de paiement et rebasculer sur "CB" en mode de paiement.
