### ISSUE TITLE
corrigé upload v 1.2 avec la v1.3

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#201]

**Comment by itkg-ndecraene** [comment]
@vschoener La méthode pushShipment() utilisée dans install1.2.0 a évolué depuis cette version (avec la lib php), j'ai fixé en supprimant le fichier install1.2.0 mais c'est moche vu qu'on a créé un tag et une release pour la 1.2. On peut éventuellement supprimer la version complètement.

**Comment by vschoener** [comment]
@quentinjunior Quel est le bug ? Car cette méthode est aussi utilisé lors de l'installation du module et ne cause aucun problème.

**Comment by vschoener** [comment]
[oyst.zip](https://github.com/oystparis/oyst-prestashop/files/1111637/oyst.zip)
