### ISSUE TITLE
As Oyst, I want to change ECMAScript 6 code to ECMAScript 5

### ISSUE THREAD

**Issue by jney** [oystparis/oyst-prestashop#202]
https://github.com/oystparis/oyst-prestashop/blob/99fdb9eae3a625143eb5dc84dd3eddb39872f671/views/js/OystOneClick.js#L24

https://caniuse.com/#feat=es6-class

**Comment by vschoener** [comment]
Is it really worth it ? Only 3 percents of the french population use ie11... I think we can let it that way and focus on more important tasks.

Don't you think ?

For information, before using ecma 6 on this project, I looked the page you provided to chose the right decision.

**Comment by jney** [comment]
it means it doesn't work **at all** in ie. it definitely worth the fix

**Comment by jney** [comment]
@nicolaschenet can you update the file?

**Comment by vschoener** [comment]
Ok.
