### ISSUE TITLE
Déplacer la cdt du non affichage du produit si product_available=0

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#204]
Certains thèmes surcharge la valeur product_available et la mette à 0. Par conséquent l'affichage du bouton 1-click ne s'affiche pas. 

Il faut déplacer cette condition pour qu'elle ne soit plus impactée par les thèmes des marchands

![pasted image at 2017_06_22 06_56 pm](https://user-images.githubusercontent.com/27730079/27648565-3e78fbce-5c2f-11e7-84b6-06728c84ec4b.png)

**Comment by vschoener** [comment]
Alright, j'ai une idée pour éviter de se baser sur une variable js (sensé être obligatoire et nécessaire par PrestaShop)
