### ISSUE TITLE
Presta 1.5 il y a 2 boutons de remboursement

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#21]
![image](https://cloud.githubusercontent.com/assets/25003742/24210987/068c216a-0f2b-11e7-995e-c6d9f31dada2.png)

**Comment by jonasmaumene** [comment]
Il faudrait supprimer le bouton de gauche

**Comment by FabienSerny** [comment]
Corrigé sur la branche feat-freepay

**Comment by jney** [comment]
@jonasmaumene a clore ?

**Comment by jonasmaumene** [comment]
en effet
