### ISSUE TITLE
Reset error

### ISSUE THREAD

**Issue by Nightmare75** [oystparis/oyst-prestashop#221]
[PrestaShop] Fatal error in module OystApiConfiguration:
Uncaught exception 'Exception' with message 'The url was not set for the environment .' in C:\Users\Chris-Anthony\Documents\www\prestashop_1.5.6.3\modules\oyst\vendor\oyst\oyst-php\src\Api\OystApiConfiguration.php:135 Stack trace: #0 C:\Users\Chris-Anthony\Documents\www\prestashop_1.5.6.3\modules\oyst\vendor\oyst\oyst-php\src\Api\OystApiClientFactory.php(79): Oyst\Api\OystApiConfiguration->getApiUrl() #1 C:\Users\Chris-Anthony\Documents\www\prestashop_1.5.6.3\modules\oyst\vendor\oyst\oyst-php\src\Api\OystApiClientFactory.php(42): Oyst\Api\OystApiClientFactory::createClient('catalog', false, NULL) #2 C:\Users\Chris-Anthony\Documents\www\prestashop_1.5.6.3\modules\oyst\src\Factory\AbstractShipmentServiceFactory.php(50): Oyst\Api\OystApiClientFactory::getClient('catalog', false, 'PrestaShop-1.3....', false, NULL) #3 C:\Users\Chris-Anthony\Documents\www\prestashop_1.5.6.3\modules\oyst\src\Service\InstallManager.php(301): Oyst\Factory\AbstractShipmentServiceFactory::get(Object(Oyst), Object(Context), Object(DbPDO)

**Comment by vschoener** [comment]
Il n'y a pas d'erreur sur ça, le zip que tu as fourni était un ancien.

**Comment by Nightmare75** [comment]
J'ai refais un test, ça affiche "Cannot install this module" mais le module est bien reset.
