### ISSUE TITLE
new feature choix du site

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#230]
Sur les sites e-marchands qui ont plusieurs boutiques, il faut qu'on puisse mettre un flag sur l'affichage des produits des boutiques. 
Mettre le choix des sites dans la conf du 1-click

**Comment by vschoener** [comment]
Pour info, un flag ne suffira pas, il faut du coup gérer le process en multi boutique de bout en bout.
- Chaque shop a une url défini (avec un slug ajouté à la fin de mémoire)
- un id_shop sera présent sur chaque produit dans une table de relation shop -> product
- Modifier la table d'export de oyst pour enregistrer cette id_shop, et modifier la logique qui touche le produit exporté. (ajout / modifier, vérifier l'affichage bouton one Click)

Surement d'autres petit truc que j'ai pas en visu dans l'immédiat.

**Comment by quentinjunior** [comment]
Si l'on change le booléen is_active lorqu'on envoie le catalogue chez oyst, cela simplifie la démarche.

Aujourd'hui ce booléen permet de ne pas afficher le bouton sur les produits désactivés, mais on peut mettre une conditions supplémentaires en passant de 1 à 0 les produits des sites désactivés dans la conf BO

**Comment by Nightmare75** [comment]
@quentinjunior Le seul avantage en mettant en place le multi-boutique pour Oyst permettra à un marchand d'utiliser Freepay & OneClick avec des comptes différents.

**Comment by quentinjunior** [comment]
ticket clos pour en faire un autre
