### ISSUE TITLE
deux boutons de remboursement en activant les retours

### ISSUE THREAD

**Issue by lamiaammiali** [OystParis/oyst-prestashop#24]
1. On active la fonction de retour produit dans prestashop:

![image](https://cloud.githubusercontent.com/assets/22000242/24289383/5ef022e6-1081-11e7-9920-ce4b4553f023.png)

On constate que lorsque active cette fonctionnalité, il y a deux boutons de remboursement qui s'affichent dans prestashop

et l'un deux permet le remboursement partiel dont nous ne voulons pas pour le moment.

![image](https://cloud.githubusercontent.com/assets/22000242/24289557/17ac4012-1082-11e7-918e-181123881e19.png)

**Comment by FabienSerny** [comment]
Corrigé sur la branche feat-freepay

**Comment by lamiaammiali** [comment]
correction ok
