### ISSUE TITLE
Statut de commande incohérent dans PS

### ISSUE THREAD

**Issue by lamiaammiali** [OystParis/oyst-prestashop#25]
1. J'effectue un remboursement depuis Prestashop 

2. Le statut de la commande passe à remboursé sur PS et (annulé coté FREEPAY  ce qui est normal car, la transaction n'est pas encore capturé)

3. je rafraîchi le BO PS du  marchand  

4. Je constate que la commande reste au statut remboursé

La commande reste au statut remboursé alors qu'elle doit passé au statut annulé une fois que PS reçois la notification d’annulation.

Piste de Nelly:

La commande n'est pas mise à jour au bon statut , car il y a eu réinstallation du plugin entre la commande et la demande de remboursement. 

![image](https://cloud.githubusercontent.com/assets/22000242/24414533/efa0a1fc-13de-11e7-99aa-2aec4c9bf947.png)

**Comment by itkg-ndecraene** [comment]
@FabienSerny Générer une clef de hash unique par marchand, en fonction de l'url de sa boutique par exemple, ou une autre donnée stable.

**Comment by FabienSerny** [comment]
La clé est toujours généré aléatoirement, en revanche, elle ne s'efface plus à la désinstallation.

**Comment by lamiaammiali** [comment]
je reproduis le bug avec la version de ce jour du pluggin

**Comment by lamiaammiali** [comment]
ce bug n'est pas majeure mais il est à traiter

**Comment by itkg-ndecraene** [comment]
Est-ce que tu as testé sur des commandes que tu as faites depuis la mise à jour? As-tu désinstaller le plugin entre temps?

**Comment by lamiaammiali** [comment]
j'ai reproduis le bug avec une commande que j'ai effectué avant de réinstaller le nouveau pluggin

**Comment by itkg-ndecraene** [comment]
Okay je vais jeter un oeil aux logs.

**Comment by lamiaammiali** [comment]
j'ai tenté le remboursement avec le dernier pluggin

**Comment by lamiaammiali** [comment]
ID de transaction 549

**Comment by itkg-ndecraene** [comment]
Problème de clef de hash regénérée car installation du plugin 1.0 après avoir désinstallé la 0.8.

**Comment by lamiaammiali** [comment]
ok testé
