### ISSUE TITLE
QA: la photo ne s'affiche pas sur la page de félicitations

### ISSUE THREAD

**Issue by jonasmaumene** [oystparis/oyst-prestashop#299]
![image](https://user-images.githubusercontent.com/25003742/29961418-e435b9dc-8eff-11e7-9fdb-d781c8012c55.png)

**Comment by quentinjunior** [comment]
Fonctionne sur 1.5 : 
![image](https://user-images.githubusercontent.com/27730079/29961653-964ef250-8f00-11e7-9aa3-224467558f5d.png)
