### ISSUE TITLE
Création produit

### ISSUE THREAD

**Issue by itkg-ndecraene** [OystParis/oyst-prestashop#31]

**Comment by vschoener** [comment]
@quentinjunior Pourquoi l'avoir réouvert ? La tâche permettant de créer le produit est sur une autre demande.

**Comment by vschoener** [comment]
J'ai rattaché sa PR

**Comment by quentinjunior** [comment]
Cette fonctionnalité marche, mais elle est très dangereuse sans la synchronisation du produit.
du coup je close mais je créé un ticket pour désactivé cette fonctionnalité.


Le marchand pourra toujours ajouter un produit et relancer la synchronisation de son catalogue
