### ISSUE TITLE
Commande 1C créée en statut paiement par chèque 

### ISSUE THREAD

**Issue by jonasmaumene** [oystparis/oyst-prestashop#366]
**Prévenir Eole dès que le pb est fixé** 

Le client ci dessous se plaint que les commandes 1C sont créée dans le statut paiement par chèque. 

Version du module 1.6

Peut t on fixer ce pb? 

Bonjour, Monsieur Jazil Rahmouni - Oyst Freepay,
Suite à votre appel téléphonique d'hier jeudi et à l'installation du bouton "One click" sur le site vivrenaturellement.com:
Le bouton "Paiement One Click" a certes été installé sur notre site, mais imparfaitement, car les commandes avec paiements "One click" ou "Freepay" apparaissent avec le statut "Paiement par chèque" ce qui fausse toute la comptabilité pour ces commandes. (Ce problème avait déjà existé à la première installation).
Cette erreur ou ce défaut d'installation (le travail ne semble pas terminé!) est donc à corriger rapidement, car cela nous créée des problèmes à répétition... Toutes ces commandes mal affectées (probablement par défaut de création du statut "Paiement avec one click") devront être corrigées. A Midi, ce vendredi 201/10, nous voyons aux dernières commandes effectuées sur notre site que ce problème persiste...
Notre webmaster "Renaud" a essayé de vous joindre par téléphone à plusieurs reprises, et il tombe toujours sur votre répondeur...
Par ailleurs, le bouton "One click" sur le site, dans un premier temps en rose, est passé au vert. Tout bien considéré, nous pensons qu'il est mieux de le remettre en rose, ce qui améliore sa visibilité pour les clients.
Merci de votre attention et de faire rapidement le nécessaire. Renaud, notre webmaster, a déjà créé un accès spécifique pour votre technicien. Si besoin, reprendre contact avec lui pour avoir un accès.
Cordialement,
Jacob & Rebecca

**Comment by rbenezra** [comment]
Actuellement dans oyst/src/Service/OrderService.php : 
![image](https://user-images.githubusercontent.com/32451092/31879170-d8cbcd38-b7dc-11e7-8b64-631d41604142.png)
la variable PS_OS_PAYMENT définie le moyen de payment. 
ETQP OC/FP je dois forcer le payement par carte bancaire et arrêter de m'appuyer sur la valeur de cette variable.
