### ISSUE TITLE
Réorganisation de l'onglet OneClick

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-prestashop#384]
Créer des sous-onglet pour tous les menu.  
![image](https://user-images.githubusercontent.com/32451092/32366516-ba1fab2a-c07e-11e7-9438-cd69f1bc4523.png)

- [ ] Ajouter un bouton sauvegarder pour chaque sous onglet.

- [ ] Réininitialisé pour la personnalisation bouton.

- [ ] Mettre "Paramètre avancés" en dernier sous onglet.

Pour le design de la fenêtre regroupant les sous-onglets on peut se baser sur : 
![image](https://user-images.githubusercontent.com/32451092/32366658-4f787ab2-c07f-11e7-95ff-4bdbb628df3f.png)

**Comment by feyromain** [comment]
- [ ] Supprimer le délai dans la configuration 1Click

- [ ] Changer **délai** par **délai de commande**

- [ ] Traduction pour  l'order before paiement par **Création de la commande avant le paiement Freepay**

- [ ] Traduction onglet **1-Click** par **1Click**

- [ ] Ajouter bouton pour désactiver les produits

- [ ] Afficher les boutons activations/désactivation dans paramètres avancés

**Comment by jonasmaumene** [comment]
@rbenezra c'est du travail de cochon tes screenshots ! Fais nous un truc plus propre :)
