### ISSUE TITLE
Erreur d'arrondi 

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-prestashop#395]
### ETQM je configure les prix en HT, sur client/groupes/Client : 
![capture](https://user-images.githubusercontent.com/32451092/32733428-836dc5e4-c88f-11e7-8d2f-3e74ea2406d6.PNG)
et les arrondis en "arrondir le total" : 
![capture](https://user-images.githubusercontent.com/32451092/32733508-bd2b650c-c88f-11e7-8748-409cb52e894d.PNG)

ETQC je commande sur 11rupt "Robe imprimée" en OC et que je modifie la quantité en *6 sur la modale.

En tant que marchand sur le BO marchand statut erreur de payement : 
![capture](https://user-images.githubusercontent.com/32451092/32733868-bd2d605e-c890-11e7-9722-c984534c0c42.PNG)

**Comment by jonasmaumene** [comment]
Ok, mais quel est le fonctionnement attendu?
