### ISSUE TITLE
Groupe client réduction

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-prestashop#396]
ETQM je configure un groupe client avec une réduction (10% par exemple).
J'y mets un client. 
Pour ce client, lorsque je fais une commande OneClick. En front sur la modale les prix s'affichent correctement. Un item à 45 euros apparaîtra bien à 40.5 euros. 

La commande arrive en erreur de payement dans le BO marchand (6euros de frais de port) : 
![capture](https://user-images.githubusercontent.com/32451092/32738068-19f828fe-c89c-11e7-8cad-05a5bb9af9ef.PNG)

**Comment by jonasmaumene** [comment]
Il faut préciser le fonctionnement attendu et valider ensemble avec Romain par tél jeudi 30 novembre. 

1. On attache en priorité une commande à un user via son id de user prestashop (il faut passer l'id dans le contexte). 
2. On attache ensuite la commande au user presta via son email. Il faut implémenter le endPoint des règles panier. 
3. Il y a des impacts lib à prévoir.

@rbenezra il faut faire 1 ticket pour le point 1 et 1 ticket pour le point 2. Eventuellement un ticket lib pour le point 3. A valider avec les devs.
