### ISSUE TITLE
Récupération id_user prestashop à partir du mail Oyst

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-prestashop#413]
# ETQP je veux pouvoir rattacher un compte Oyst à un compte prestashop à partir de l'adresse mail du client renseigné sur son compte Oyst.

Si un client n'est pas loggé sur son compte prestashop lors d'un achat oneclick. Il faut réussir à récupérer l'id_user prestashop afin de lui faire bénéficier des réductions auxquelles il a droit.

1ère étape : récupérer l'id_user prestashop (s'il existe) à partir de son mail Oyst.
2ème étape : récupérer l'url OC contenant les prix actualisés à partir de l'user ID.
3ème étape : utiliser le order.cart.estimate pour afficher les bons prix sur la modale OC : https://one-click-api.readme.io/reference#règles-paniers

**Exemple d'event à envoyer :** 
```
POST /oneclick/v2/orders/authorize HTTP/1.1
Host: api.sandbox.oyst.eu
Authorization: Bearer YOUR_API_KEY
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
Postman-Token: 72685cc7-0556-ec1a-cc21-b170dd75daf9

{  
   "product":{...},
   "order":{...},
   "notifications":{
   		"events":["order.cart.estimate"],
   		"url" : "URL_A_APPELER_POUR_RECUPERER_LES_PRIX_ACTUALISES"
   }
}
```

**Empty case :** 
dans le cas où l'email Oyst n'est associé à aucun user prestashop, on crée en base prestashop un compte client associé à ce mail, on y récupère l'user_id et on utilise order.cart.estimate avec cette user_ID (par soucis d'uniformité du code).

**Comment by StefBrito** [comment]
Déjà géré
