### ISSUE TITLE
Remboursement OneClick

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-prestashop#416]
# ETQM je veux pouvoir rembourser les commandes OC depuis mon back-office marchand.

Actuellement, pour rembourser une commande oneclick, un marchand est obligé de se connecter à son BO Freepay. Il faudrait qu'il puisse procéder à un remboursement depuis son back-office marchand avec un bouton "Remboursement 1-Click".

Même modèle que "Remboursement Freepay" sauf qu'il n'y a pas d'étape d'annulation puisque la capture est instantanée. 

[Checker avec Cyril remboursement partiel depuis order API]

https://github.com/oystparis/oyst-prestashop/issues/402

Même corner case pour les bons de réductions.

**Tech details :** 
![image](https://user-images.githubusercontent.com/32451092/35282961-2f05bba6-0057-11e8-9621-f2ec1ae9dcdc.png)
https://one-click-api.readme.io/reference#remboursement-partiel

**Comment by feyromain** [comment]
Quel statut doit être affecter lors d'un remboursement ?

**Comment by StefBrito** [comment]
release
