### ISSUE TITLE
Remboursement partiel

### ISSUE THREAD

**Issue by itkg-ndecraene** [OystParis/oyst-prestashop#44]
En tant que marchand, je peux rembourser partiellement une commande depuis prestashop

### Affichage des boutons
Avant que la commande ne soit capturée, le système affiche un bouton "Cancel order" (fonctionnement iso actuel "Total refund").

![screenshot-8](https://cloud.githubusercontent.com/assets/10598916/25377732/a02cad0c-29a8-11e7-93df-030bf5bc0742.png)

Après que la commande soit capturée, le système affiche un bouton "Total refund" (fonctionnement iso existant) et un bouton "Partial Refund".

![screenshot-6](https://cloud.githubusercontent.com/assets/10598916/25377739/a65290a2-29a8-11e7-879a-350b9bc5edd2.png)

Si la commande est totalement remboursée aucun des boutons ne s'affichent.

![screenshot-9](https://cloud.githubusercontent.com/assets/10598916/25377747/ab0c560a-29a8-11e7-88e0-3621d23e6d3d.png)

### Process de remboursement
Lorsque que le marchand clique sur le bouton "Partial refund.", le focus de l'écran est mis sur le bloc produit de la fiche commande (natif prestashop) :

![screenshot-2](https://cloud.githubusercontent.com/assets/10598916/25377790/c7fbb5f8-29a8-11e7-83f4-37f1cd8a0384.png)

Le marchand peut choisir les produits ou le montant qu'il souhaite rembourser (natif Prestashop)

A la validation par le marchand, le module FreePay emet une demande de remboursement à l'api de paiement FreePay,

**Si la réponse de l'api est positive**

Un message de succès au marchand
![screenshot-4](https://cloud.githubusercontent.com/assets/10598916/25377845/f005942e-29a8-11e7-8b68-9a967b72a8d2.png)

On ajoute une notification de paiement (color : coral) avec le montant remboursé.

Si la commande est totalement remboursée :
Le statut de la commande passe à "Remboursé"

Sinon (si il reste des fonds sur la commande)
Le statut de la commande passe à "Partiellement remboursé" (à créer)

![screenshot-5](https://cloud.githubusercontent.com/assets/10598916/25377860/ff399940-29a8-11e7-96b0-d0ba1235a015.png)

**Si la réponse de l'api est négative**

On affiche le message d'erreur suivant en haut de la page commande:
"Une erreur est survenue : [Message renvoyé par la paiement API]"

### Misc
Masquer le bouton "Edit" sur les produits du bloc "Product"
![screenshot-10](https://cloud.githubusercontent.com/assets/10598916/25377892/0f0b2622-29a9-11e7-877d-60d215120767.png)

**Comment by quentinjunior** [comment]
Tout est ok pour moi, et on pousse en prod lundi matin
