### ISSUE TITLE
Rendre fraudscoring administrable

### ISSUE THREAD

**Issue by StefBrito** [oystparis/oyst-prestashop#455]
# Actuellement les marchands se plaignent du fonctionnement du fraudscoring qui retarde l'envoie de leurs commandes nous allons (temporairement ?) le rendre administrable et laisser la possibilité au marchand de le désactiver. 

Rajouter une check-box pour le désactiver: ignorer les notifications de fraudscoring, ne plus utiliser les statuts dédiés, récupérer l'ancien fonctionnement.

**Comment by rbenezra** [comment]
wording : "Activer le gestionnaire de fraude."
