### ISSUE TITLE
Gestion des stocks

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-prestashop#456]

**Comment by StefBrito** [comment]
3 Choses importantes :

- Impossible d'acheter si il n'y a plus de stock ou si la quantité choisie sur le front est supérieure au stock 
  (Renvoyer vers le message d'erreur natif de Prestashop)
  Donner la possibilité d'acheter Hors stock au client. 
- Décrémenter le stock lorsque la modale est lancée, réincrémenter le stock si la commande est annulée
- Incrémenter et décrémenter le stock dans la modale

**Comment by StefBrito** [comment]
done
