### ISSUE TITLE
Bouton page panier items

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-prestashop#457]
# ETQM je veux pouvoir activer le bouton oneclick sur une page récap panier.

Un marchand doit pouvoir activer depuis son back-office le bouton OC sur la page récap panier. 
![image](https://user-images.githubusercontent.com/32451092/35286528-8a16cf7c-0060-11e8-960d-569b79058c6d.png)

**Wording :**
"Activation le bouton page panier" et "Cochez cette option pour afficher le bouton 1-Click sur la page récapitulative du panier." en-dessous de la check-box. 

**Tech details :**
L'api permet l'envoie de plusieurs produits en même temps par OC sur la route "/v2/orders/authorize" : 
```
POST /oneclick/v2/orders/authorize HTTP/1.1
Host: api.sandbox.oyst.eu
Authorization: Bearer YOUR_API_KEY
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
Postman-Token: 55e53c69-638b-2faf-115a-f56a17fb3152

{  
   "products":[{...},{...},{...}],
   "notifications": {
     "url": "http://www.your_notification_url.com"
   }
}
```

**Transporteur:**
On fonctionnera sur le même principe que le end point shipping.
Primary puis fallback au hasard dans les "home delivery disponible". 

**Produits démat:**
/!\ Si un panier contient du démat et du matérialisé, on considérera (pour Oyst) que la commande est matérialisée.
Si un panier contient que du démat, l'order sera considérée comme dématérialisée.
**En attente d'un custom bouton BO pour les boutons page panier: [NEW STORY]**
![image](https://user-images.githubusercontent.com/32451092/35287207-15e35966-0062-11e8-802c-1aa01b41eda3.png)

**Comment by StefBrito** [comment]
release
