### ISSUE TITLE
[QA] 1.7.1

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-prestashop#464]
# Presta 1.6
- [x] Ne pas mettre de point à "Activer le gestionnaire de fraude"
![image.png](https://images.zenhubusercontent.com/59d35d9db0222d5de47a0eeb/bcc73679-f6bc-46e2-9374-d393c664fa4e)

- [x] Lors d'une mise à jour du module vers 1.7.1 le changement de wording des nom de statuts n'est plus pris en compte : 
![image.png](https://images.zenhubusercontent.com/59d35d9db0222d5de47a0eeb/7a8c5a28-38ce-4014-a158-9d051e578263)
"En attente de check-fraud" --> "En attente de vérification fraude chez Oyst" 
voir ticket #435

- [x] Sur un achat Freepay qui passe pas au fraudscoring automatique (qui ne reçoit pas la notif de FS OK dès la création d'order et qui est donc envoyée en validation manuelle), si everkey refuse la commande et renvoie un FS KO, la modification de statut se fait bien et la notification est enregistrée en base. Si il revient sur sa décision, et envoie un fraudscoring OK cette notification n'est pas enregistrée en base et le changement de statut vers "paiement accepté" ne se fait pas.
Sur presta 1.5 on a pas ce problème ce qui suppose que la deuxième notif de FS est bien envoyée par l'api et que le plugin ne la récupère pas.

# Presta 1.5
- [x] Aligner "Activer le gestionnaire de fraude" : 
![image](https://user-images.githubusercontent.com/32451092/35223988-aec6c440-ff83-11e7-9507-c0775c122d9f.png)

**Comment by StefBrito** [comment]
@feyromain as tu pris en compte ces modifications ?

**Comment by StefBrito** [comment]
Pris en compte à closer
