### ISSUE TITLE
Smart Button

### ISSUE THREAD

**Issue by StefBrito** [oystparis/oyst-prestashop#469]
Smart Bouton qui s’adapte au site marchand en répliquant la forme de son bouton Ajouter au Panier. Paramètre disponible depuis BO CMS :

Couleur (déjà fait)
Largeur, Hauteur (déjà fait)

Border (coin rond ou carrée)
Activation smart button (Yes,No)

**Comment by StefBrito** [comment]
```data-smart='true/false'````
-
```data-borderradius='true/false'````
-
```data-theme='{default/inverted}'````
-
```data-color='hexa'````


Directement récupéré nativement par rapport au bouton panier :
```data-height'pixel'````
-
```data-width='pixel'````

**Comment by feyromain** [comment]
data-theme='{default/inverted}'

Il est pas gérer le paramètre la ?

On est d'accord que si le client a cocher smart button. On doit récupérer la width du bouton panier et l'affecter à data-width ?

Pour le margin comment on doit gérer la chose ?

**Comment by StefBrito** [comment]
release
