### ISSUE TITLE
Bouton apparait sur produit simple en rupture de stock

### ISSUE THREAD

**Issue by mathieupierre** [oystparis/oyst-prestashop#471]
CMS version: Prestashop 1.5.6.X 
Le bouton 1-Click button n’apparaît pas sur les produits sans déclinaisons : 

![produitsimple1](https://user-images.githubusercontent.com/35369184/35562907-31680710-05b5-11e8-98c4-cd2b502bdb00.PNG)

Le champ déclinaison est bien vide sur ce produit : 

![produitsimple3](https://user-images.githubusercontent.com/35369184/35562950-64a39842-05b5-11e8-9efa-4aa871a67d49.PNG)
 
Lorsque que l'on procède à un achat :

![produitsimple2](https://user-images.githubusercontent.com/35369184/35562926-49bfac96-05b5-11e8-8df3-345841d2d19b.PNG)

Le problème n'existe pas sur les produits avec déclinaisons dans Prestashop 1.5.6.X

**Comment by StefBrito** [comment]
done
