### ISSUE TITLE
Rendre visible les tables de notifications dans le BO

### ISSUE THREAD

**Issue by StefBrito** [oystparis/oyst-prestashop#481]
Stocker toutes les notifications 1C et FP et les rendre visible dans le BO

**Comment by feyromain** [comment]
Pour la partie rendre visible. On devons nous afficher ces informations ?
Création d'une page oyst dans le BO ?

**Comment by StefBrito** [comment]
Ouais rajoute un onglet qui nous permet de voir les tables de la DB

**Comment by StefBrito** [comment]
release
