### ISSUE TITLE
Impossible importer le catalogue sur prestashop 1.5 : Fatal error

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#49]
![image](https://cloud.githubusercontent.com/assets/25003742/25281885/1b3407ea-26af-11e7-9e14-02fdaa1e0e02.png)

**Comment by vschoener** [comment]
@itkg-ndecraene Cela ne fonctionne pas avec la branche que j'ai créé contenant oneClick et l'export ?
(Ce qui serait bizarre vu que j'ai moi même testé les 2 de bout en bout.)

**Comment by vschoener** [comment]
Fixed
