### ISSUE TITLE
Bug lors de la suppression des produits. 

### ISSUE THREAD

**Issue by mathieupierre** [oystparis/oyst-prestashop#527]
2 marchands se plaignent de voir une Fatal Error lors de la suppression de produits. 

Cokitec a la 1.9.1 et Piils la 1.7.0 du module

![Screenshot-2018-2-21 https piils fr.png](https://images.zenhubusercontent.com/5a6b517a4b5806bc2bc46ee5/454941f7-0d3e-4bf9-8d02-91e5f60705f2)

**Comment by StefBrito** [comment]
Plus d'actualités. (mauvaise installation du module)
