### ISSUE TITLE
Impossible de supprimer le plugin oneclick 1.1.0 de Prestashop

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#53]
Voici l'erreur qui remonte quand je clique sur "supprimer"

Fatal error: Call to a member function uninstall() on boolean in /home/borntonebw/www/controllers/admin/AdminModulesController.php on line 572
[PrestaShop] Fatal error in module AdminModulesController:
Call to a member function uninstall() on boolean

![image](https://cloud.githubusercontent.com/assets/25003742/25338314/1b51d7b4-28ff-11e7-9d78-3453ee3bc4e6.png)

**Comment by vschoener** [comment]
@FabienSerny Any idea ?

**Comment by vschoener** [comment]
Apparement non reproductible..

**Comment by jney** [comment]
@jonasmaumene toujours reproductible de ton coté ?

**Comment by jonasmaumene** [comment]
nope je ferme
