### ISSUE TITLE
Clé API 1click (différente de la clé FreePay)

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#55]
En tant que marchand, je peux renseigner 2 clé API FreePay et 1 click différente

**Comment by vschoener** [comment]
Pourrait-on avoir plus d'infos sur cette demande ?

**Comment by jonasmaumene** [comment]
Yes aujourd'hui on utilise la même clé API pour FreePay et 1click. 

On aimerait pouvoir renseigner une clé différente pour le 1click.

**Comment by vschoener** [comment]
Ah d'accord vous utilisez pas la même clé API pour le marchand.. Pas possible d'utiliser la même ? Ou l'historique le permet pas ?

**Comment by jonasmaumene** [comment]
On veut que les transactions 1click et freepay remontent dans 2 backoffices
différents. On a pas encore fait de BO 1click alors le plus simple c'est
d'utiliser 2 clé API différentes.

**Comment by quentinjunior** [comment]
Ok, je close
