### ISSUE TITLE
Etude faisabilité module light Presta 1.7

### ISSUE THREAD

**Issue by StefBrito** [oystparis/oyst-prestashop#603]

**Comment by jonasmaumene** [comment]
Etude de faisabilité pour brancher Oyst sans faire de module sur prestashop 1.7. 

TO DO :
Faire une proposition sans installation.
Faire une proposition ou l'on pose un module générique qui permet l'ouverture de portes à Oyst.

Pour chaque propositon. Rédiger une diagramme d' "archi" de ce type : 
https://www.draw.io/?state=%7B%22ids%22:%5B%221Dhm4k9Z0G_pg-tdFN7pvKgGPRV-RizxV%22%5D,%22action%22:%22open%22,%22userId%22:%22114223927478093938166%22%7D#G1LB7PFjBGSqkGQNJSkFNjLCqSKGkjfTfX
