### ISSUE TITLE
Mettre le tag dans le module Presta 1.7

### ISSUE THREAD

**Issue by jonasmaumene** [oystparis/oyst-prestashop#614]
### En tant que connecteur, je peux pousser un tag sur toutes les pages de la boutique prestashop via un appel POST. 

TODO : 
Implémenter un point d'entrée pour que le connecteur puisse pousser le script front. 
Le script est ensuite chargé sur toutes les pages de la boutique. 

Entrée : 
url du script

Sortie : 
Standard REST

**Comment by kevin-snt** [comment]
[Oyst-2.0-API.postman_collection.zip](https://github.com/oystparis/oyst-prestashop/files/1966639/Oyst-2.0-API.postman_collection.zip)

**Comment by StefBrito** [comment]
Good pour moi
