### ISSUE TITLE
Route oyst/order/{order_id}

### ISSUE THREAD

**Issue by jonasmaumene** [oystparis/oyst-prestashop#615]
Renvoyer les statuts de la commande
Pouvoir changer ce statut

**Comment by kevin-snt** [comment]
[Oyst-2.0-API.postman_collection.zip](https://github.com/oystparis/oyst-prestashop/files/1966804/Oyst-2.0-API.postman_collection.zip)

**Comment by StefBrito** [comment]
good pour moi
