### ISSUE TITLE
Compatibilité avec le module Chronopost officiel

### ISSUE THREAD

**Issue by jonasmaumene** [oystparis/oyst-prestashop#641]
https://docs.google.com/document/d/1ieLBYeUNxl71FrHIVydbtFoPIvftZ1zgZwodec0uOiY/edit

**Comment by jonasmaumene** [comment]
le module : https://addons.prestashop.com/fr/transporteurs/19561-chronopost-officiel.html

**Comment by StefBrito** [comment]
En attente de la connexion à l'API chronopost
