### ISSUE TITLE
Bug shipment 404 -> Peinture destock

### ISSUE THREAD

**Issue by mathieupierre** [oystparis/oyst-prestashop#646]
## Context

Hotfix -> Motif de churn (top 3 marchand du parc)
Bug Shipment 404 Peinture-Destock - Stock

## Specification

Parfois un shipment 404 persistant (sur tous les produits + page panier) arrive sur peinture destock. Celui-ci reste une dizaine de minutes à partir du moment où un shipment 404 avéré se produit (sur un produit réellement en rupture de stock).

L'erreur : "Produit Indisponible" apparait, ensuite on change de fiche produit et lorsque l'on essaye de faire un achat 1C sur d'autres produits un shipment 404 "Problème de livraison l'adresse n'est pas prise en charge" remonte.

Test effectué pour reproduire l'erreur : 

Commander en 1-Click un produit dont il reste 4 quantité en stock -> passer la quantité au dessus de 4 dans la modale

Un aperçu des logs du module : 

![image.png](https://images.zenhubusercontent.com/5a6b517a4b5806bc2bc46ee5/32dad672-6777-4e5e-9309-4b76db7c118c)

L'erreur dans AWS : 

 "data": {
        "code": "stock-unavailable",
        "message": "Unvailable stock"
    },

Cela provient de l'ID produit remonté qui n'est pas la bonne. 
L'ID renvoyé par l'API (celle-ci correspond au produit visité avant..)  "product_reference": "4954;10172",  
VS l'ID réel du produit : "product_reference": "5274;10652",

Ci-dessous les logs AWS : 
https://docs.google.com/document/d/1y0d2MzlGQBnSzjoQMvJqWFatja7P-pYK6c-wUOqw1lU/edit

Test effectué : 
Commander en 1-Click un produit dont il reste 4 quantité en stock -> passer la quantité au dessus de 4 dans la modale

**Comment by StefBrito** [comment]
Plus d'actualités
