### ISSUE TITLE
L'import ne termine pas sur prestashop 1.5

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#65]
Lorsque je clique sur le bouton import, le bandeau import en cous reste, alors qu'il est terminé. 

![image](https://cloud.githubusercontent.com/assets/25003742/25521851/73aa6188-2c01-11e7-884b-903e661c1ce9.png)

![image](https://cloud.githubusercontent.com/assets/25003742/25521890/8fb0a3e2-2c01-11e7-8e72-33d0eb0872e5.png)

**Comment by vschoener** [comment]
De ce que je lis, il n'a pas commencé non plus, je n'ai pas vu de requête venant de Oyst demandant la liste des produit, tu aurait du voir un gros pavé s'afficher montrant le détail complet.
LE notifyImport, c'est quand tu cliques sur le bouton demandant l'import à Oyst.

**Comment by jney** [comment]
a croiser avec @cyrilhagege @david-berichon

**Comment by vschoener** [comment]
@quentinjunior Tu peux tester le module sur une 1.5 et nous faire un retour ? 

Merci :)
