### ISSUE TITLE
Réorganisation des paramètres avancés de l'interface de paramétrage du plugin

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#66]
## Valeur par défaut :

Activer FreePay : Coché 
URL Succès : Confirmation de commande
URL Erreur : Erreur de paiement
Activer 1click : Décoché
Clé API 1click : Vide 
Environnement : Prod

### Par défaut:

![image](https://cloud.githubusercontent.com/assets/27730079/26410226/f21781f8-40a2-11e7-88be-e50bc4c646b1.png)

### Puis quand je clique sur paramètres avancés:

![image](https://cloud.githubusercontent.com/assets/27730079/26410246/ffbf790a-40a2-11e7-9647-c03fd964fa06.png)

**Comment by itkg-ndecraene** [comment]
@jonasmaumene On enlève le bouton "Afficher/Masquer les options avancées"?

**Comment by itkg-ndecraene** [comment]
Fini, mais il faudra qu'en faisant le #55 on applique ce design (pareil pour le bouton de synchro du catalogue)

**Comment by quentinjunior** [comment]
ok, je close
