### ISSUE TITLE
ETQ Marchand, je peux entrer mes frais de livraison via le plugin OneClic

### ISSUE THREAD

**Issue by Marcpepe** [oystparis/oyst-prestashop#68]
Réalisation : 
Ajouter dans le plugin un formulaire qui permette au marchand d'ajouter un moyen de livraison (bouton "+") et renseigner ses frais de port (article leader, articles followers) et son seuil de livraison gratuite  (possibilité de le détecter automatiquement ?)

![image](https://cloud.githubusercontent.com/assets/4925054/25955377/6188ae84-3669-11e7-810d-99c7eedc6966.png)

Ce formulaire peut être ajouté à l'emplacement suivant : 

![image](https://cloud.githubusercontent.com/assets/4925054/25711484/506de5a8-30ef-11e7-8536-3daf0f198a18.png)

**Comment by quentinjunior** [comment]
![image](https://user-images.githubusercontent.com/27730079/26929675-cecef8e8-4c5a-11e7-934b-ab844d40ca76.png)

**Comment by quentinjunior** [comment]
@itkg-ndecraene comme tu l'as bien remarqué, il faut ajouter un delay
On le propose en jours pour le marchand et en back tu convertis en heures (x24) pour l'envoyer à Oyst

**Comment by itkg-ndecraene** [comment]
Okay. Je fais ça.

**Comment by quentinjunior** [comment]
Incohérence des frais de livraisons entre ce qui est configuré sur le BO et ce qui est proposé au client:
![image](https://user-images.githubusercontent.com/27730079/27089956-218fb900-505c-11e7-82e9-4676de750cd3.png)

**Comment by quentinjunior** [comment]
Contraintes à ajouter -> #166
