### ISSUE TITLE
As merchant, hide the OneClick carrier during the classic checkout

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#69]
![image](https://cloud.githubusercontent.com/assets/25003742/25712294/8bd02afa-30f1-11e7-95c7-1f377c93da15.png)

**Comment by quentinjunior** [comment]
Cela ne fonctionne pas sur un 1click checkout

**Comment by quentinjunior** [comment]
Ok pour moi, je close
