### ISSUE TITLE
Impossible d'activer le bouton 1click sur Prestashop 1.5

### ISSUE THREAD

**Issue by jonasmaumene** [OystParis/oyst-prestashop#74]
![image](https://cloud.githubusercontent.com/assets/25003742/25751555/bf040c7e-31b5-11e7-869d-a0b1cc519b96.png)

**Comment by jonasmaumene** [comment]
Lorsque je clique sur la case à cocher et que je valide. Un message de succes s'affiche et la cas est décochée.

**Comment by vschoener** [comment]
Fixed
