### ISSUE TITLE
Infos requises en plus dans la page html pour trk.10ru.pt

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#80]
## Détails:

En tant que Oyst, en lisant le code source des pages HTML du site du marchand, je dois pouvoir connaître:
1. La version du module freepay utilisée
1. Un flag nous indiquant si le module FreePay est activé (quand la case est coché, pas seulement si le module est installé)
1. Un flag nous indiquant si le module OneClick est activé (quand la case est coché, pas seulement si le module est installé)
1. Un flag nous indiquant si la clé API FreePay est renseignée
1. Un flag nous indiquant si la clé API OneClick est renseignée

### To Do:

Faire une "balise" dans lequel figure toutes ces informations pour que la data puisse recupérer facilement ce qu'elle souhaite

**Comment by quentinjunior** [comment]
Remarques de Florian:
-Tu choisis un ID assez long et bizarre pour qu'il soit unique, pour qu'il puisse le récupérer
-Tu choisis le format pour les informations
- Tu mets la balise dans le header pour que ce soit dans toutes les pages

**Comment by quentinjunior** [comment]
Dédoubler ces informations pour le 1-click

**Comment by itkg-ndecraene** [comment]
![meta_data](https://cloud.githubusercontent.com/assets/10598916/26821151/bdeaa66e-4aa5-11e7-99c7-45e9964b30a5.png)
