### ISSUE TITLE
remboursement partiel possible une seule fois 

### ISSUE THREAD

**Issue by lamiaammiali** [OystParis/oyst-prestashop#81]
je suis sur une boutique PS 1.6

1.J'effectue un remboursement partiel depuis PS sur une commande contenant 2 articles 

2.Je constate bien la demande de refund en base de donné

3.Le statut dans PS passe de remboursement partiel en cours  à remboursée partiellement.

4.j'effectue un second remboursement sur le second article 

Le remboursement ne s'effectue pas .

Seul le premier est pris en compte 
![image](https://cloud.githubusercontent.com/assets/22000242/25993304/de8d5466-3709-11e7-9029-a4918d4345db.png)

**Comment by quentinjunior** [comment]
## décision prise:

* En tant que marchand je fais un remboursement partiel

Alors les boutons remboursement standard et remboursement partiel ne sont plus disponibles cf #96

**Comment by quentinjunior** [comment]
Ok, je close
