### ISSUE TITLE
Caché le bouton cancel order une fois qu'on a déjà cliqué dessus une fois

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#82]
## détails:

* Dans le BO PrestaShop Commandes. Je peux annuler une commande avec le bouton cancel order:

![image](https://cloud.githubusercontent.com/assets/27730079/25993559/9d3da7c6-370a-11e7-8a37-dac220f327b6.png)

* Je clique dessus et l'état change : annulation en cours

* Je peux encore cliquer sur le bouton cancel order.
* J'obtiens logiquement une erreur de la part de PrestShop

![image](https://cloud.githubusercontent.com/assets/27730079/25993664/07829196-370b-11e7-9a09-2045885ef9da.png)

## A faire:

Il faut donc désactiver ce bouton ou le cacher pour que le marchand ne puisse cliquer dessus qu'une seule fois.

**Comment by lamiaammiali** [comment]
ok pour moi sur 1.6

**Comment by quentinjunior** [comment]
ok pour moi sur 1.5

**Comment by lamiaammiali** [comment]
ok je clôture
