### ISSUE TITLE
Wording boutons: anglais -> francais

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#83]
## Détails :

Certains boutons sont en anglais et d'autres en français. 
Il faut tous les mettre en français comme par exemple: 
* standard refund -> remboursement total
* cancel order -> annuler la commande

![image](https://cloud.githubusercontent.com/assets/27730079/25997868/93150280-371e-11e7-9f3e-7d377ebf78c1.png)

**Comment by lamiaammiali** [comment]
ok pour moi
