### ISSUE TITLE
Bannière rouge  : Attention Commande payée deux fois 

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#84]
En tant que marchand, lorsque je regarde le détail d'une commande. J'observe dans la section paiement une bannière rouge indiquant: attention paiement double:

![image](https://cloud.githubusercontent.com/assets/27730079/26004861/87ed3b8e-3737-11e7-8ee4-3c59942d0ad5.png)

On remarque que les horaires des paiements correspondent aux horaires des états de la commande:
14h39 et 14h45

![image](https://cloud.githubusercontent.com/assets/27730079/26004839/6ceffd3a-3737-11e7-98c6-b89fbbfdfd94.png)

**Comment by lamiaammiali** [comment]
celui ci - est toujours reproductible 
![image](https://cloud.githubusercontent.com/assets/22000242/26111546/aef94d96-3a55-11e7-827d-272941a5a5af.png)

**Comment by itkg-ndecraene** [comment]
Oui j'avais oublié que les statuts n'étaient pas supprimé entre deux installations.
Je les supprimerai pour que tu puisses faire une installation propre.

**Comment by quentinjunior** [comment]
Ok pour moi sur 1.5

**Comment by quentinjunior** [comment]
ok, je close
