### ISSUE TITLE
Erreurs lors d'une incrémentation négative pour le remboursement partiel

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#85]
## Contexte:

En tant que marchand quand:
*  je clique sur le bouton remboursement partiel
* je remplis le champ des quantités par un nombre négatif (ici -1)
* je remplis le champ du montant  (ici 100e)

![image](https://cloud.githubusercontent.com/assets/27730079/26049349/f9be05de-395a-11e7-8057-b0da4fc89fda.png)

* je clique sur valider et j'arrive sur la page suivante

![image](https://cloud.githubusercontent.com/assets/27730079/26049355/01f87b62-395b-11e7-9ddf-14ca845d8a6f.png)

* je rafraichis la page et j'envoie un nouveau formulaire

![image](https://cloud.githubusercontent.com/assets/27730079/26049361/073e95f2-395b-11e7-9ca8-9904089e3efb.png)

* j'arrive sur le BO PrestaShop avec le remboursement partiel en attente

![image](https://cloud.githubusercontent.com/assets/27730079/26049371/0bcde41a-395b-11e7-80b7-7bb356ae4400.png)

* Quelques secondes plus tard, mon remboursement partiel est confirmé

![image](https://cloud.githubusercontent.com/assets/27730079/26049452/5e906b32-395b-11e7-82cc-2ec49582995d.png)

### Conséquences:

* Depuis le BO FreePay un remboursement d'une valeur de 100 euros a été effectuée

![image](https://cloud.githubusercontent.com/assets/27730079/26049526/98e2a6ce-395b-11e7-834a-40155e53058d.png)

* Depuis le BO PrestaShop on n'observe pas le remboursement

![image](https://cloud.githubusercontent.com/assets/27730079/26049509/8d3cb6ac-395b-11e7-9b72-e51d4d1f99c9.png)

**Comment by itkg-ndecraene** [comment]
Fixed by #86

**Comment by quentinjunior** [comment]
ok, je close
