### ISSUE TITLE
Pas de plafond pour l'incrémentation du nombre d'articles lors d'un remboursement partiel

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#86]
En tant que marchand quand:
* je fais un remboursement partiel
* je peux indiquer un nombre supérieur d'articles à rembourser et finaliser le remboursement

![image](https://cloud.githubusercontent.com/assets/27730079/26005278/e0cb3a7a-3738-11e7-8e69-6896abcb2aa8.png)

![image](https://cloud.githubusercontent.com/assets/27730079/26005293/eb0e3960-3738-11e7-975d-a05ac65c515f.png)

**Comment by itkg-ndecraene** [comment]
@quentinjunior C'est le fonctionnement normal de prestashop. Tu constateras le même bug sur des commandes non FreePay.

**Comment by quentinjunior** [comment]
Ah merde... pas moyen de figer l'incrémentation? car les deux tickets
d’après (85 et 87) en découlent

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-05-15 17:55 GMT+02:00 itkg-ndecraene <notifications@github.com>:

**Comment by itkg-ndecraene** [comment]
@quentinjunior Ok j'ai surchargé le comportement par une méthode javascript qui check à la fois la quantité saisie et le montant. Si ce n'est pas bon la valeur est remise à 0. Ça te va?

**Comment by quentinjunior** [comment]
Oui parfait !

**Comment by quentinjunior** [comment]
Attention petit beug, certaines tranches de nombre ne sont pas prises en compte (souvent entre 10 et 23)


![image](https://cloud.githubusercontent.com/assets/27730079/26209089/230cbd0c-3bec-11e7-997b-60d91c1f316f.png)

**Comment by quentinjunior** [comment]
Ok, je close
