### ISSUE TITLE
Bug compta côté prestashop

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#87]
### Détails:

En tant que marchand, lorsque je fais un remboursement partiel depuis le BO PrestaShop et que:
* j'indique un nombre (q) supérieur  au nombre d'articles de la commande (p)  (q>p)
* j'indique un prix (x)

Alors dans la section produit, il est écrit que le remboursement a été d'un montant de (p*x(/q))

PS: il n'y a pas de bug côté BO FreePay

#### Exemple 1:

* ll y a un produit (p=1).
* J'écris dans le champ 5 (q=5)
* J'écris 20 euros (x=20)

Alors dans le paiement je vois écrit remboursé 4 euros ((20/5)*1)

![image](https://cloud.githubusercontent.com/assets/27730079/26006125/9be95aba-373b-11e7-8291-42d1ae458470.png)

#### Exemple 2:

* ll y a trois produits dans la commande (p=3).
* J'écris dans le champ 5 (q=5)
* J'écris 10 euros (x=10)

Alors dans le paiement je vois écrit remboursé 6 euros ((10/5)*3)

![image](https://cloud.githubusercontent.com/assets/27730079/26006297/2dfeaa0e-373c-11e7-9ed9-9b6b47498361.png)

**Comment by itkg-ndecraene** [comment]
Fixed by #86

**Comment by quentinjunior** [comment]
ok, je close
