### ISSUE TITLE
Intégration de la FAQ FreePay depuis le BO  PrestaShop

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-prestashop#88]
## Détails:

En tant que marchand je peux consulter la FAQ depuis le BO FreePay côté PrestaShop

Le lien doit amener le marchand directement sur la question vis à vis de l'installation de FreePay sur PrestaShop

![image_inte_presta](https://cloud.githubusercontent.com/assets/27730079/26057186/d3bbaef4-3978-11e7-82dd-e21ebf648c77.png)

**Comment by itkg-ndecraene** [comment]
@quentinjunior Possible d'avoir le lien de la FAQ?
