### ISSUE TITLE
As Merchant, I want a check on the oneClick button for the products

### ISSUE THREAD

**Issue by vschoener** [oystparis/oyst-prestashop#93]
I want the the button displayed only if the product has been sent to Oyst.

**Comment by vschoener** [comment]
For information, we need to review the the way to sent product, specifically using the variations way.

Actually a variation is a new product.

**Comment by quentinjunior** [comment]
Tu ne devais gérer les variations pour ce ticket? Et il n'est pas prioritaire

**Comment by quentinjunior** [comment]
Ok pour moi
