### ISSUE TITLE
En tant que marchand je n'arrive pas à installer FreePay sur PrestaShop 1.5

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#94]
## Contexte:

En tant que marchand, depuis le BO PrestaShop 1.5, je peux importer un module correctement (fichier zip). Mais je n'arrive pas à télécharger FreePay pour la configuration de mon compte.

![image](https://cloud.githubusercontent.com/assets/27730079/26110707/687ab50a-3a53-11e7-8f68-09e5adb4d539.png)

**Comment by itkg-ndecraene** [comment]
A priori c'est réparé. Ce que j'ai fait pour que ça fonctionne :
- copier/coller le module dézippé (1.1.0) sur le ftp directement
- installer le module
- uploader le module 1.2.0
- supprimer le module 1.2.0
- uploader le module 1.1.0

**Comment by quentinjunior** [comment]
Ok pour moi.
