### ISSUE TITLE
Masquer le bouton remboursement standard une fois que la demande est faite

### ISSUE THREAD

**Issue by lamiaammiali** [OystParis/oyst-prestashop#95]
Lorsqu'on effectue une demande de remboursement standard le bouton reste actif jusqu'à la confirmation du remboursement.

On souhaite masquer le bouton lorsqu'on effectue une demande de remboursement standard.

![image](https://cloud.githubusercontent.com/assets/22000242/26110978/213e8d96-3a54-11e7-9d9b-e4d642de73d1.png)

**Comment by quentinjunior** [comment]
Pas fix :

![image](https://cloud.githubusercontent.com/assets/27730079/26209738/e85ba586-3bed-11e7-904d-0fcf2f199000.png)

![image](https://cloud.githubusercontent.com/assets/27730079/26209748/f0892cc4-3bed-11e7-83b3-a279a0516be5.png)

**Comment by quentinjunior** [comment]
ok, je close
