### ISSUE TITLE
Masquer le bouton remboursement standard après une demande de remboursement partiel

### ISSUE THREAD

**Issue by lamiaammiali** [OystParis/oyst-prestashop#96]
Lorsqu'on effectue une demande de remboursement partiel le bouton remboursement standard  reste actif jusqu'à la confirmation du remboursement partiel 

On souhaite masquer le bouton remboursement standard  lorsqu'on effectue une demande de remboursement Partiel.

![image](https://cloud.githubusercontent.com/assets/22000242/26113348/943e9c7c-3a5a-11e7-9398-33b646b9a105.png)

**Comment by quentinjunior** [comment]
ok, je close
