### ISSUE TITLE
l'export de produit ne fonctionne pas 

### ISSUE THREAD

**Issue by lamiaammiali** [OystParis/oyst-prestashop#97]
j'installe la dernière version du pluggin 1-click

j'effectue l'export du catalogue, j'obtiens un log de succès 

mais l'export ne se fait pas 

![image](https://cloud.githubusercontent.com/assets/22000242/26148460/fb9d4f34-3af6-11e7-8d1d-a6e22d2ebca7.png)

**Comment by vschoener** [comment]
@quentinjunior Tu valides que nous avons testé dernièrement et que tout fonctionne ?

**Comment by quentinjunior** [comment]
Oui je valide et je close le ticket
