### ISSUE TITLE
La synchronisation du catalogue ne fonctionne pas

### ISSUE THREAD

**Issue by quentinjunior** [OystParis/oyst-prestashop#98]
En tant que marchand, mon catalogue ne se synchronise pas chez Oyst.

![image](https://cloud.githubusercontent.com/assets/27730079/26157547/c7ef5b96-3b19-11e7-9dce-3aa4ec15443b.png)

**Comment by quentinjunior** [comment]
Erreur 404: le temps de réponse est aléatoire car depuis staging on appelle l'url marchand qui est en local sur le pc de Vincent, la connexion est impossible.

**Comment by cyrilhagege** [comment]
Bug corrige. Probleme de timeout lors de la notification a prestashop

**Comment by vschoener** [comment]
@quentinjunior Les tests de ce matin ont été concluants :) Je te laisse confirmer et clôturer ce ticket.

**Comment by vschoener** [comment]
Pour info, le ticket a déjà été créé par @lamiaammiali
